### ISSUE TITLE
[BUG] latest gak

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/graph-app-kit#100]
Latest `gak` (`graphistry/graph-app-kit-st      v2.40.11-11.5                            22ac66583738   5 days ago      22.5GB`) breaking staging

@DataBoyTX  Can you triage as you've been in this code most recently? Not sure if we need to land one of the PRs or what, maybe @tanmoyio can help once we've identified the issue

Logs:
```
graphistry-graph-app-kit-public-1 exited with code 1
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:03.076242647Z pwd: /app
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:03.077334594Z .
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:03.077335946Z ./requirements-app.txt
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:03.077336137Z ./requirements-system.txt
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:03.077337399Z ./conda-app.sh
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771781161Z Traceback (most recent call last):
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771784688Z   File "/opt/conda/envs/rapids/bin/streamlit", line 5, in <module>
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771785138Z     from streamlit.web.cli import main
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771785539Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/streamlit/__init__.py", line 70, in <module>
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771786090Z     from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771787353Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/streamlit/delta_generator.py", line 90, in <module>
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771787774Z     from streamlit.elements.arrow_altair import ArrowAltairMixin
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771788244Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/streamlit/elements/arrow_altair.py", line 35, in <module>
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771789988Z     from altair.vegalite.v4.api import Chart
graphistry-graph-app-kit-private-1  | 2023-05-18T05:29:05.771790589Z ModuleNotFoundError: No module named 'altair.vegalite.v4'
graphistry-graph-app-kit-public-1   | 2023-05-18T05:29:05.933702640Z ModuleNotFoundError: No module named 'altair.vegalite.v4'
```

And:

```
ubuntu@graphistry-cloud-v24011-run44:/var/graphistry$ docker run --rm -it --entrypoint=/bin/bash 22ac66583738
(rapids) root@822be0976f04:/app# ls
conda-app.sh  requirements-app.txt  requirements-system.txt
(rapids) root@822be0976f04:/app# cat ^C
(rapids) root@822be0976f04:/app# cat requirements-app.txt 
### your custom requirements here
#protobuf==3.13.0(rapids) root@822be0976f04:/app# cat requirements-system.txt 
streamlit==1.12.0
protobuf==3.18
graphistry==0.27.1

################
#
#  Per-DB
#
################

### Neptune
gremlinpython==3.4.10
sshtunnel==0.1.5

### TigerGraph
pyTigerGraph  # Unpinned as TG Cloud is rapidly moving
plotly  # for demos(rapids) root@822be0976f04:/app# 
```

**Comment by DataBoyTX** [comment]
this was fixed with the following PR: https://github.com/graphistry/graph-app-kit/pull/97
